version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-portfolio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-portfolio}
      POSTGRES_DB: ${POSTGRES_DB:-portfolio}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-09-27T15-22-50Z
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    env_file:
      - ../.env.example
    depends_on:
      - postgres
      - minio
    ports:
      - "8000:8000"

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.web
    env_file:
      - ../.env.example
    depends_on:
      - api
    environment:
      - FASTAPI_URL=http://api:8000
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    ports:
      - "8080:8080"

volumes:
  postgres-data:
  minio-data:
