FROM python:3.11-slim

WORKDIR /app

COPY api /app/api
RUN pip install --upgrade pip && pip install -e /app/api[dev]

ENV PYTHONPATH=/app

CMD ["uvicorn", "api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
